Repository greenbone/openvas-scanner, pull requests merged in 2021-12, with the labels that each got.

#977 Fix filling msghdr for sendmsg
  nasl/nasl_frame_forgery.c
Labels: backport-to-stable, backport-to-middleware

#986 Replace own implementation of get_iface_index with if_nametoindex()
  misc/pcap.c
Labels: backport-to-stable, backport-to-middleware

#964 Add read_ssh_blocking
  nasl/nasl_ssh.c
Labels: backport-to-stable, backport-to-middleware

#991 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-to-stable, backport-to-oldstable, backport-to-middleware

#995 Change: extend cert_query() nasl function to get the public key algorithm
  nasl/nasl_cert.c
Labels: backport-to-stable, backport-to-middleware

#996 Handle string encoding conversion fail
  misc/plugutils.c
Labels: backport-to-stable, backport-to-middleware

#997 Fix: Check 'reader' for NULL before trying to unreference it during cleanup
  misc/table_driven_lsc.c
Labels: backport-to-middleware
