Repository greenbone/openvas-scanner, pull requests merged in 2021-09, with the labels that each got.

#853 Add nasl function sftp_enabled_check()
  CHANGELOG.md
  nasl/nasl_init.c
  nasl/nasl_ssh.c
  nasl/nasl_ssh.h
Labels: backport-to-21.04

#854 Fix issues found by CodeQL
  CHANGELOG.md
  nasl/md4.c
  nasl/nasl_cmd_exec.c
  nasl/nasl_isotime.c
  nasl/nasl_misc_funcs.c
  nasl/nasl_var.c
  src/hosts.c
Labels: backport-to-21.04, backport-to-middleware

#862 Improve logging.
  CHANGELOG.md
  nasl/nasl_ssh.c
Labels: backport-to-21.04, backport-to-middleware

#861 Fix changelog
  CHANGELOG.md
  nasl/nasl_cmd_exec.c
Labels: backport-to-master, backport-to-middleware

#885 fix error msg
  CHANGELOG.md
  src/openvas.c
Labels: backport-to-master
