Repository greenbone/openvas-scanner, pull requests merged in 2021-08, with the labels that each got.

#819 [20.08] Add signing to workflow ...
  .github/workflows/release-pontos-patch.yml
Labels: make patch release

#820 [21.04] Add signing to workflow ...
  .github/workflows/release-pontos-patch.yml
Labels: make patch release

#821 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-to-21.04, backport-to-master, backport-to-middleware

#826 Changed defaults for installation locations
  CHANGELOG.md
  CMakeLists.txt
Labels: backport-to-21.04, backport-to-master, backport-to-middleware

#832 Fix interrupted scans
  CHANGELOG.md
  src/attack.c
  src/pluginlaunch.c
  src/pluginlaunch.h
Labels: backport-to-20.08, backport-to-master, backport-to-middleware
