Repository greenbone/openvas-scanner, pull requests merged in 2022-03, with the labels that each got.

#1044 Change: extended the nasl functions ereg(), egrep(), eregmatch().
  nasl/nasl_text_utils.c
Labels: backport-to-middleware

#1057 Change: consider a malformed regex as a nasl parse error for built-in RE_MATCH and RE_NOMATCH
  nasl/nasl_grammar.y
  nasl/nasl_tree.c
  nasl/nasl_tree.h
Labels: backport-to-middleware

#1059 Remove: remove MD5 support from feed integrity check
  nasl/nasl_grammar.y
Labels: backport-to-middleware

#1060 Change: nasl linter error count message
  nasl/nasl-lint.c
Labels: backport-to-stable, backport-to-middleware

#1071 Update INSTALL.md
  INSTALL.md
Labels: backport-to-stable
