Repository greenbone/openvas-scanner, pull requests merged in 2022-08, with the labels that each got.

#1150 Fix: sync Notus
  tools/greenbone-nvt-sync.in
Labels: backport-to-stable

#1156 Remove: unnecessary code in libs CMakeLists.txt files
  misc/CMakeLists.txt
  nasl/CMakeLists.txt
Labels: backport-to-stable

#1160 Fix "Nmap scan type requires root privileges" error with container
  .docker/prod.Dockerfile
Labels: backport-to-main

#1164 Fix: PLugin process keeps scanning after manually stopping task
  src/attack.c
  src/pluginlaunch.c
Labels: backport-to-stable

#1168 Change: Use docker/meta-action for container tags and labels
  .github/workflows/container.yml
Labels: backport-to-stable, backport-to-oldstable

#1176 Fix: determine SSL/TLS support on services
  nasl/nasl_builtin_find_service.c
Labels: backport-to-stable
