Repository greenbone/openvas-scanner, pull requests merged in 2022-02, with the labels that each got.

#1017 Fix stop scan.
  src/openvas.c
Labels: backport-to-middleware

#1013 Refactor: add hostname to unable to SSL authenticate message
  misc/network.c
Labels: backport-to-stable

#1024 Fix possible g_memdup() silent memory truncation.
  misc/network.c
  misc/plugutils.c
  misc/support.h
  nasl/nasl_cert.c
  nasl/nasl_crypto.c
  nasl/nasl_crypto2.c
  nasl/nasl_misc_funcs.c
  nasl/nasl_packet_forgery.c
  nasl/nasl_packet_forgery_v6.c
  nasl/nasl_scanner_glue.c
  nasl/nasl_socket.c
  nasl/nasl_text_utils.c
  nasl/nasl_var.c
Labels: backport-to-stable, backport-to-middleware

#1020 Add flag to set cipher suite preferences on a TLS session
  misc/network.c
  misc/network.h
  nasl/nasl_builtin_find_service.c
  nasl/nasl_socket.c
Labels: backport-to-stable, backport-to-middleware

#1035 Change: handle Fatal alert during handshake.
  misc/network.c
  nasl/nasl_builtin_find_service.c
Labels: backport-to-stable, backport-to-middleware

#1045 Change: remove unnecessary variable in nasl/CMakeLists.txt
  nasl/CMakeLists.txt
Labels: backport-to-stable, backport-to-middleware

#1048 Fix: sigsegv backtrace log
  src/sighand.c
Labels: backport-to-stable, backport-to-middleware
