Repository greenbone/openvas-scanner, pull requests merged in 2024-10, with the labels that each got.

#1733 Fix: setting stack buffer to NULL
  src/pluginlaunch.c
Labels: patch_release

#1732 Fix: unit-tests in openvas-scanner
  .docker/prod-oldstable.Dockerfile
  .docker/prod-testing.Dockerfile
  .github/install-openvas-dependencies.sh
  .github/workflows/dependency-review.yml
  rust/Cargo.lock
  rust/Cargo.toml
  rust/cross.Dockerfile
  rust/cross_aarch64.Dockerfile
  rust/data/nasl_syntax/smb_nt.inc
Labels: no_release

#1736 Fix: linking issues within docker images
  .docker/prod-oldstable.Dockerfile
  .docker/prod-testing.Dockerfile
  .docker/prod.Dockerfile
Labels: no_release

#1737 Add: NASL builtin functions for rsa
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/nasl/builtin/cryptographic/mod.rs
  rust/src/nasl/builtin/cryptographic/rsa.rs
  rust/src/nasl/builtin/cryptographic/tests/mod.rs
  rust/src/nasl/builtin/cryptographic/tests/rsa.rs
Labels: minor_release

#1749 Fix: issue-1746: missing init phase
  rust/src/osp/response.rs
Labels: no_release
