Repository greenbone/openvas-scanner, pull requests merged in 2024-09, with the labels that each got.

#1704 Add: nasl built regex library, regex nasl functions and tests.
  rust/Cargo.lock
  rust/Cargo.toml
  rust/nasl-builtin-regex/Cargo.toml
  rust/nasl-builtin-regex/README.md
  rust/nasl-builtin-regex/src/lib.rs
  rust/nasl-builtin-regex/tests/regex.rs
  rust/nasl-builtin-std/Cargo.toml
  rust/nasl-builtin-std/src/lib.rs
  rust/nasl-builtin-string/src/lib.rs
  rust/nasl-builtin-string/tests/string.rs
  rust/nasl-syntax/src/token.rs
Labels: minor_release

#1695 Fix: change HEAD endpoint
  rust/doc/openapi.yml
  rust/openvasd/src/controller/entry.rs
Labels: no_release

#1697 Use nasl function macro for builtin socket functions
  rust/Cargo.lock
  rust/nasl-builtin-network/Cargo.toml
  rust/nasl-builtin-network/src/lib.rs
  rust/nasl-builtin-network/src/network.rs
  rust/nasl-builtin-network/src/socket.rs
Labels: no_release

#1703 Add: nasl builtin functions for kb manipulation
  rust/Cargo.lock
  rust/nasl-builtin-knowledge-base/Cargo.toml
  rust/nasl-builtin-knowledge-base/README.md
  rust/nasl-builtin-knowledge-base/src/lib.rs
  rust/nasl-builtin-knowledge-base/tests/kb.rs
  rust/openvasd/src/feed.rs
  rust/storage/src/item.rs
  rust/storage/src/lib.rs
Labels: no_release

#1708 Fix: load the feed metadata from an existing json file
  rust/scannerctl/src/error.rs
  rust/scannerctl/src/interpret/mod.rs
  rust/storage/src/lib.rs
Labels: no_release

#1709 Add: NASL bultin functions for isotime
  rust/Cargo.lock
  rust/Cargo.toml
  rust/nasl-builtin-isotime/Cargo.toml
  rust/nasl-builtin-isotime/README.md
  rust/nasl-builtin-isotime/src/lib.rs
  rust/nasl-builtin-isotime/tests/isotime.rs
  rust/nasl-builtin-std/Cargo.toml
  rust/nasl-builtin-std/src/lib.rs
Labels: no_release

#1718 Fix logging of used openvasd storage.
  rust/openvasd/src/main.rs
  rust/openvasd/src/storage/file.rs
  rust/openvasd/src/storage/inmemory.rs
  rust/openvasd/src/storage/redis.rs
Labels: no_release

#1719 Fix: scan progress for openvas scanner type.
  rust/models/src/host_info.rs
  rust/openvas/src/openvas.rs
  rust/osp/src/response.rs
Labels: no_release

#1726 Fix: CI. libssh dependency
  .docker/prod-testing.Dockerfile
Labels: patch_release

#1722 Fix: enable-get-scans
  rust/src/openvasd/config.rs
Labels: patch_release

#1730 Change: Update gvm-libs image in prod.Dockerfile and build.Dockerfile
  .docker/build.Dockerfile
  .docker/prod-oldstable.Dockerfile
  .docker/prod-testing.Dockerfile
  .docker/prod.Dockerfile
Labels: no_release
