Repository greenbone/openvas-scanner, pull requests merged in 2024-11, with the labels that each got.

#1750 Fix: mark scan as failed on fetch result errors
  rust/doc/openapi.yml
  rust/src/openvasd/controller/entry.rs
  rust/src/openvasd/response.rs
  rust/src/openvasd/scheduling.rs
  rust/src/scanner/mod.rs
Labels: no_release

#1754 Fix: made host, hostname, port, test_id, severity optional
  rust/Cargo.lock
  rust/src/openvas/result_collector.rs
  rust/src/osp/response.rs
Labels: patch_release

#1738 Add: more cryptography nasl function
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/nasl/builtin/cryptographic/bf_cbc.rs
  rust/src/nasl/builtin/cryptographic/mod.rs
  rust/src/nasl/builtin/cryptographic/rc4.rs
  rust/src/nasl/builtin/cryptographic/tests/bf_cbc.rs
  rust/src/nasl/builtin/cryptographic/tests/mod.rs
  rust/src/nasl/builtin/cryptographic/tests/rc4.rs
  rust/src/nasl/builtin/mod.rs
Labels: minor_release

#1761 Fix: Overflow when parsing large version numbers in notus
  rust/src/notus/packages/mod.rs
  rust/src/notus/packages/rpm.rs
Labels: patch_release

#1767 Fix: notus result generation.
  misc/table_driven_lsc.c
Labels: patch_release

#1757 NASL builtin function for open privileged sockets with udp and tcp
  doc/manual/nasl/built-in-functions/network-functions/open_priv_sock_tcp.md
  rust/Cargo.toml
  rust/examples/socket/tcp_priv.nasl
  rust/examples/socket/udp_priv.nasl
  rust/src/nasl/builtin/network/README.md
  rust/src/nasl/builtin/network/network.rs
  rust/src/nasl/builtin/network/network_utils.rs
  rust/src/nasl/builtin/network/socket.rs
  rust/src/nasl/builtin/network/tcp.rs
  rust/src/nasl/builtin/network/udp.rs
Labels: minor_release

#1769 Fix: `get_version()` of packages containing the epoch
  rust/src/notus/packages/deb.rs
  rust/src/notus/packages/ebuild.rs
  rust/src/notus/packages/rpm.rs
  rust/src/notus/packages/slack.rs
Labels: patch_release

#1702 Add: NASL bultin functions for certificate handling
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/nasl/builtin/cert/mod.rs
  rust/src/nasl/builtin/mod.rs
  rust/typos.toml
Labels: no_release
