Repository greenbone/openvas-scanner, pull requests merged in 2024-06, with the labels that each got.

#1652 Fix: Option.unwrap on None value when unknown preference is set
  rust/openvas/src/pref_handler.rs
Labels: patch_release

#1656 Fix: use edge instead of unstable as a default version
  .docker/build.Dockerfile
  .docker/prod-oldstable.Dockerfile
  .docker/prod-testing.Dockerfile
  .docker/prod.Dockerfile
Labels: no_release

#1654 Fix: forks to often when reading same KB in different scripts
  nasl/nasl.c
Labels: no_release

#1653 Add: possibility to configure openvasd without mTLS and without api-key
  rust/openvasd/src/controller/entry.rs
  rust/openvasd/src/controller/mod.rs
Labels: no_release

#1642 Add: NASL builtin function DES
  rust/Cargo.lock
  rust/nasl-builtin-cryptographic/Cargo.toml
  rust/nasl-builtin-cryptographic/src/des.rs
  rust/nasl-builtin-cryptographic/src/lib.rs
  rust/nasl-builtin-cryptographic/tests/des.rs
Labels: minor_release

#1658 Fix: openvas-nasl has issues executing subsequent .nasl scripts
  misc/plugutils.c
Labels: patch_release

#1657 Fix: Set the right status when a scan fails because an invalid host list
  rust/openvas/src/openvas.rs
  src/attack.c
  src/attack.h
  src/openvas.c
Labels: patch_release
