Repository greenbone/openvas-scanner, pull requests merged in 2024-05, with the labels that each got.

#1635 Add: push container to ghcr.io
  .github/workflows/control.yml
  .github/workflows/push-container.yml
Labels: no_release

#1641 Fix: scannerctl feed transile -p ... -r ...
  rust/scannerctl/src/feed/mod.rs
Labels: patch_release

#1644 CI: trying to fix unable to push based on rebase
  .github/workflows/release.yml
Labels: patch_release, no_release

#1628 Add: some tests for notus and for http2 builtin nasl functions
  rust/examples/feed/notus/advisories/sha256sums
  rust/examples/feed/notus/advisories/windows.notus
  rust/examples/feed/notus/products/sha256sums
  rust/examples/feed/notus/products/windows_11_home.notus
  rust/examples/http2.nasl
  rust/openvasd/src/storage/file.rs
Labels: no_release

#1637 Add: methology for simulating forking behaviour
  rust/Cargo.lock
  rust/examples/get_kb_item.nasl
  rust/feed/src/update/mod.rs
  rust/nasl-builtin-cryptographic/tests/aes_cbc.rs
  rust/nasl-builtin-cryptographic/tests/aes_ccm.rs
  rust/nasl-builtin-cryptographic/tests/aes_cmac.rs
  rust/nasl-builtin-cryptographic/tests/aes_ctr.rs
  rust/nasl-builtin-cryptographic/tests/aes_gcm.rs
  rust/nasl-builtin-cryptographic/tests/hash.rs
  rust/nasl-builtin-cryptographic/tests/hmac.rs
  rust/nasl-builtin-host/tests/hostname.rs
  rust/nasl-builtin-knowledge-base/src/lib.rs
  rust/nasl-builtin-knowledge-base/tests/kb.rs
  rust/nasl-builtin-misc/tests/misc.rs
  rust/nasl-builtin-raw-ip/tests/frame_forgery.rs
  rust/nasl-builtin-raw-ip/tests/packet_forgery.rs
  rust/nasl-builtin-std/src/lib.rs
  rust/nasl-builtin-std/tests/array.rs
  rust/nasl-builtin-string/tests/string.rs
  rust/nasl-builtin-utils/src/context.rs
  rust/nasl-interpreter/Cargo.toml
  rust/nasl-interpreter/README.md
  rust/nasl-interpreter/src/assign.rs
  rust/nasl-interpreter/src/call.rs
  rust/nasl-interpreter/src/declare.rs
  rust/nasl-interpreter/src/fork_interpreter.rs
  rust/nasl-interpreter/src/include.rs
  rust/nasl-interpreter/src/interpreter.rs
  rust/nasl-interpreter/src/lib.rs
  rust/nasl-interpreter/src/loop_extension.rs
  rust/nasl-interpreter/src/operator.rs
  rust/nasl-interpreter/tests/description.rs
  rust/nasl-interpreter/tests/local_var.rs
  rust/nasl-syntax/src/lexer.rs
  rust/nasl-syntax/src/naslvalue.rs
  rust/scannerctl/src/interpret/mod.rs
  rust/storage/src/retrieve.rs
Labels: minor_release

#1648 Fix: deadlock when deleting running scan
  rust/openvasd/src/scheduling.rs
Labels: patch_release
